name: GI-GameNotice System

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout data repo
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Save settings.json
        run: echo "{ \"name\":\"${{ secrets.NAME }}\", \"webhook\":\"${{ secrets.WEBHOOK }}\", \"language\":\"${{ secrets.LANGUAGE }}\" }" > settings.json

      - name: Execute main script
        run: |
          python3 main.py
          if [ -f "commit.txt" ];
          then
            echo "COMMIT_TITLE=$(<commit.txt)" >> $GITHUB_ENV
            echo $(<commit.txt)
          fi

      - name: Commit update
        if: env.COMMIT_TITLE != ''
        run: |
          git add -N log
          git add -N README.md
          if ! git diff --exit-code --quiet
          then
            git config user.name c2tr
            git config user.email 80561604+github-actions@users.noreply.github.com
            git add log
            git add README.md
            git commit -m "${{ env.COMMIT_TITLE }}"
            git push
          fi
